### ISSUE TITLE
Plot comparison in a single figure not working for plots other than barplots

### ISSUE THREAD

**Issue by javier-coronel-snkeos** [clearml/clearml#1298]
## Describe the bug

I find very useful the comparison of experiments and I'm trying to use this as well to get meaningful comparisons across different datasets. 
However, the comparison of plots for the same kind of figure (histograms, boxplots) in two different dataset is not working as expected. Currently it's working only for barplots. 
I'm using plotly to add the figures to a dataset.
![image](https://github.com/user-attachments/assets/47158dc3-f931-47b6-b6d9-262a6b44ebb6)

## To reproduce
Here's a snippet to reproduce the creation of a dataset with two plots (the figure above). 
When comparing the datasets in the UI, the barplot shows the comparison of the two datasets in a single figure, nevertheless that doesn't happen for the boxplot figures:
```Python
import random

import pandas as pd
import plotly.express as px
from clearml import Dataset

for _data_version in range(2):
    dataset = Dataset.create(dataset_name="my_dataset", dataset_project="my_project")

    data = {"sample_id": [f"id_{i+1}" for i in range(10)], "duration": [random.uniform(0, 10) for _ in range(10)]}
    df = pd.DataFrame(data)

    bar_fig = px.bar(df, x="sample_id", y="duration", title="Duration per Sample")
    bar_fig.update_layout(xaxis_title="Sample ID", yaxis_title="Duration", legend_title_text="Legend")
    dataset.get_logger().report_plotly("Bar Plot", "Duration per Sample", bar_fig)

    box_fig = px.box(df, y="duration", title="Boxplot of Duration")
    box_fig.update_layout(yaxis_title="Duration", legend_title_text="Legend")
    dataset.get_logger().report_plotly("Box Plot", "Boxplot of Duration", box_fig)

    dataset.finalize()
```

## Expected behaviour
Here's what I would expect of a boxplot comparison of two datasets for instance:
![image](https://github.com/user-attachments/assets/e0c754bf-5a3e-4302-af86-cfdf9f8b68e5)
I would expect that a comparison of plots with the same name and type should be displayed in a single figure (which works for bar plots) instead of in two different figures.

I've tried with different parameters in the layout and arguments for plotly, but haven't been able to solve it. I would appreciate any help.

## Environment
* Server type: self hosted
* ClearML SDK Version: 1.16.2
* ClearML Server Version: WebApp: 3.22.0-131 • Server: 3.22.0-1461 • API: 2.30.
* Python 3.11.5
* OS: WSL

**Comment by ainoam** [comment]
@javier-coronel-snkeos You'll note that this is [the stated behaviour](https://clear.ml/docs/latest/docs/webapp/webapp_exp_comparing/#plot-comparison). That said, it seems to make a lot of sense to use overlay for box-plots - We'll look into adding it to future versions.

**Comment by javier-coronel-snkeos** [comment]
Thanks @ainoam for your reply. I see, good to know this will considered for future versions, maybe also considering histograms for those overlays?

Not sure if its an expected behavior, but in the UI I can manage to compare boxplots in the same figure by doing the following:
1. Enable the data of plot 2 in figure 1
2. Enable the data of plot 1 in figure 2
3. Remove one dataset from the "versions" menu at the top
![image](https://github.com/user-attachments/assets/477858a3-64f4-44b0-9338-87036811d371)

Then the two plots are in the same figure. For me this seems more like a UI hack given that the url only includes the id of one of the datasets, and the embedded code of the figure shows the data of one plot and not the combined figure

**Comment by ainoam** [comment]
@javier-coronel-snkeos Definitely a hack-enabling bug :)
Histograms make definite sense.

**Comment by pollfly** [comment]
Hey @javier-coronel-snkeos! Just letting you know that this issue has been resolved in the recently released [clearml-server v1.17.0](https://github.com/allegroai/clearml-server/releases/tag/v1.17.0). Let us know if there are any issues :)

**Comment by IrDIE** [comment]
got latest clearml-server version
plots overlapping is still not working for radar plot

<img width="1473" height="521" alt="Image" src="https://github.com/user-attachments/assets/efdf419f-aeb3-4880-ab64-0c3544b78abb" />

**Comment by IrDIE** [comment]
got latest clearml-server version
plots overlapping is still not working for radar plot

<img width="1473" height="500" alt="Image" src="https://github.com/user-attachments/assets/5a450936-b53b-4b3d-bad9-d74a002d3556" />

**Comment by ainoam** [comment]
Not a big surprise @IrDIE, since docs state "**Line, scatter, box, and bar** graphs are compared by overlaying each metric/variant from all compared tasks' into a single comparative plot." (See earlier [comments](https://github.com/clearml/clearml/issues/1298#issuecomment-2233733709)) 🙂 
Radar plot overlay makes definite sense - we'll look into adding this in future versions.
